cc_binary(
  name = "yuna",
  srcs = [
      "main.cpp",
  ],
  deps = [
      "@com_github_gflags_gflags//:gflags",
      "@com_github_google_glog//:glog",
      "@com_google_absl//absl/types:optional",
      "@com_google_absl//absl/strings",
      "//psh-solver:simulator",
  ],
)

