version: 2

jobs:
  build-cc:
    docker:
      - image: nya3jp/icfpc2019-bazel:0.25.2-ubuntu18.04
    steps:
      - checkout
      - run: bazel --bazelrc=.circleci/bazel.rc build //...
      - run: bazel --bazelrc=.circleci/bazel.rc test //...

  build-go:
    docker:
      - image: golang:1.12
    steps:
      - checkout
      - run: go mod download
      - run: go install github.com/nya3jp/icfpc2019/cmd/...
      - run: go test github.com/nya3jp/icfpc2019/...

workflows:
  version: 2
  commit:
    jobs:
      - build-cc
      - build-go
